/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.parisnanterre.miage.tdd;

public class Dictionnaire {
    private String name ;

    public Dictionnaire(String nom) {
        this.name = nom;
    }

    public String getName() {
        return this.name;
    }

    public boolean isEmpty(){
        return false;
    }

}
