/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.parisnanterre.miage.tdd;

public class Dictionnaire {
    private String name ;

    public Dictionnaire() {
        this.name = "Example";
    }

    public String getName() {
        return this.name;
    }

}
