/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.parisnanterre.miage.tdd;

import org.junit.Before;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;

class DictionnaireTest {
    private Dictionnaire dictionary;

    @BeforeEach
    public void initialize(){
        this.dictionary= new Dictionnaire("contre");
    }

    @Test
    public void testDictionaryName(){
        assertThat(dictionary.getName(),equalTo("contre"));
    }

    @Test public void testDictionnaryIsEmpty(){
        assertThat(dictionary.isEmpty(),equalTo(true));
    }

    @Test public void testOneTranslation(){
        dictionary.addTranslation("contre","against");
        assertThat(dictionary.getTranslation("contre"),equalTo("against"));
    }

}
