/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fr.parisnanterre.miage.tdd;

import org.junit.Before;
import org.junit.jupiter.api.Test;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;

class DictionnaireTest {
    private Dictionnaire dictionary = new Dictionnaire();

    @Test
    public void testDictionaryName(){
        assertThat(this.dictionary.getName(), equalTo("Example"));
    }
}
